# Generated by Django 2.2.13 on 2020-11-05 14:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('company', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('photo', models.ImageField(upload_to='products')),
                ('price', models.IntegerField()),
                ('description', models.TextField()),
                ('publishing_end_date', models.DateTimeField(auto_now_add=True)),
                ('schooltype', models.CharField(choices=[('praktijkonderwijs', 'praktijkonderwijs'), ('vmbo', 'vmbo'), ('mbo', 'mbo'), ('hbo', 'hbo'), ('opleidingsbedrijf', 'opleidingsbedrijf')], max_length=6)),
                ('category', models.CharField(choices=[('1', '1'), ('2', '2'), ('3', '3'), ('4', '4'), ('5', '5'), ('6', '6')], max_length=6)),
                ('company', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='company.CompanyProfile')),
            ],
        ),
    ]
